### PR TITLE
Make fetchState handle unexpected response

### LINKED ISSUE #121: gatekeeper: Handle unexpected response in fetchState
We need to handle cases where the response that `fetchState` gets is not as expected.

i.e. https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/helpers/services.ts#L118 will fail with an exception if the data was something like `{"bob"}`

### LINKED ISSUE #122: gatekeeper: Ensure authenticationProgressCreator prop is used
It is unused here: https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback/custom.tsx#L70

### PR DESCRIPTION
**Pull request by p-netm**
- closes #121 , closes #122 
- Handle lack of session in response when fetchState tries fetching state.

### CODE REVIEW

File: packages/gatekeeper/src/helpers/services.ts [hunk 1]
```diff
@@ -94,15 +99,14 @@ export async function fetchUser(
 }
 
 /** some docstring */
```
Comment (moshthepitt) [inline packages/gatekeeper/src/helpers/services.ts]: Could we please write a proper docstring?

File: packages/gatekeeper/src/helpers/services.ts [hunk 2]
```diff
@@ -94,15 +99,14 @@ export async function fetchUser(
...
-  > = authenticationProgress,
-  errorCallbackFn: ErrorCallback = errorCallback
-) => {
+export const fetchState = async ({
+  url = '',
+  authenticateActionCreator = authenticateUser,
+  recordResultActionCreator = recordResult,
+  authenticationProgressCreator = authenticationProgress,
+  errorCallbackFn = errorCallback,
+  logoutActionCreator = logOutUser
```
Comment (moshthepitt) [inline packages/gatekeeper/src/helpers/services.ts]: I am not sure that I like relying on inferred types Vs statically defining them.  What are your thoughts on this?

File: packages/gatekeeper/src/helpers/services.ts [hunk 3]
```diff
@@ -94,15 +99,14 @@ export async function fetchUser(
...
-  url: string,
-  authenticateActionCreator: ActionCreator<AuthenticateAction> = authenticateUser,
-  recordResultActionCreator: ActionCreator<RecordAction> = recordResult,
-  authenticationProgressCreator: ActionCreator<
-    AuthenticationProgressAction
-  > = authenticationProgress,
-  errorCallbackFn: ErrorCallback = errorCallback
-) => {
+export const fetchState = async ({
+  url = '',
```
Comment (moshthepitt) [inline packages/gatekeeper/src/helpers/services.ts]: Can we make this function not have a default for `url`?  I want the Typescript compiler to complain when this function is called without a URL (coz it does not make sense to do so).

File: packages/gatekeeper/src/helpers/services.ts [hunk 4]
```diff
@@ -115,6 +119,13 @@ export const fetchState = async (
     })
     .then(data => {
       const { session } = data;
+      if (!session) {
+        logoutActionCreator();
+        const err = new Error('User is logged out');
+        recordResultActionCreator(false, { err });
+        authenticationProgressCreator(false);
+        return;
```
Comment (moshthepitt) [inline packages/gatekeeper/src/helpers/services.ts]: Why are we calling return this way here?  Why not throw the error, or call `errorCallbackFn`?

File: packages/gatekeeper/src/components/callback/custom.tsx [hunk 5]
```diff
@@ -3,7 +3,9 @@ import {
   authenticateUser,
```
Comment (moshthepitt) [inline packages/gatekeeper/src/components/callback/custom.tsx]: Please remove all unused imports.

File: packages/gatekeeper/dist/ducks/gatekeeper.js [hunk 6]
```diff
@@ -8,7 +8,8 @@ Object.defineProperty(exports, "__esModule", {
 exports["default"] = reducer;
 exports.getResult = getResult;
 exports.getSuccess = getSuccess;
-exports.recordResult = exports.RECORD = exports.initialState = exports.reducerName = void 0;
+exports.isWorking = isWorking;
```
Comment (moshthepitt) [inline packages/gatekeeper/dist/ducks/gatekeeper.js]: Could we please document the intended usage of `isWorking`?

File: packages/gatekeeper/src/helpers/services.ts (hunk 2 above)
Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: yeah, inferred types are weaker to statically defined types

Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: Maybe we can use a convention where required parameters are passed as ordered arguments and optional arguments are passed in as an object? cc @cKellyDesign.

Comment (moshthepitt) [reply packages/gatekeeper/src/helpers/services.ts]: that sounds like a good idea @p-netm --- how would you type such a function?

Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: the options would have to be the first argument.

Comment (moshthepitt) [reply packages/gatekeeper/src/helpers/services.ts]: why is that @p-netm ?

Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: I haven't thought this through totally, i will build a case for it and if compelling enough i will bring it up. At the moment i know it could make it easier in dealing with optional arguments, where we can use a function in modules from which we dont have access to some of the values that would be passed to optional arguments e.g
__contrived-alert__
`const findX(y, z =1, i=2) => {}`

using findX in a module that does not have acces to a value of z, but does for i

File: packages/gatekeeper/src/helpers/services.ts (hunk 1 above)
Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: done

File: packages/gatekeeper/src/helpers/services.ts (hunk 3 above)
Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: done

File: packages/gatekeeper/src/helpers/services.ts (hunk 2 above)
Comment (p-netm) [reply packages/gatekeeper/src/helpers/services.ts]: > why is that @p-netm ?

Not necessarily, I thought about it and the position of the optional arguments as an object is inconsequential to how we modify the existing code.

File: packages/gatekeeper/dist/ducks/gatekeeper.js (hunk 6 above)
Comment (p-netm) [reply packages/gatekeeper/dist/ducks/gatekeeper.js]: done
